# Test API

@demo_username = {{$dotenv APP_DEMO_USERNAME}}
@demo_password = {{ $dotenv APP_DEMO_PASSWORD }}
@demo_email = {{ $dotenv APP_DEMO_EMAIL }}

### Register account
POST http://localhost:8090/api/auth/local/register HTTP/1.1
Content-Type: application/json

{
    "username": "{{demo_username}}",
    "email": "{{demo_email}}",
    "password": "{{demo_password}}"
}

### Get all users

GET http://localhost:8090/api/users HTTP/1.1
Content-Type: application/json