services:
  db:
    image: postgres:latest
    container_name: my_db_compose
    ports:
      - "55433:5432"
    environment:
      - POSTGRES_DB=somsak
      - POSTGRES_USER=somsak
      - POSTGRES_PASSWORD=somsak
  