services:
  db:
    image: postgres:latest
    container_name: my_db_compose
    ports:
      - "55432:5432"
    environment:
      - POSTGRES_DB=somsak
      - POSTGRES_USER=somsak
      - POSTGRES_PASSWORD=somsak
        
  web:
    image: prawee/strapi:latest
    container_name: my_app_compose
    ports:
      - "8080:1337"
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=somsak
      - DATABASE_USERNAME=somsak
      - DATABASE_PASSWORD=somsak
  