services:
  db:
    image: ${DB_IMAGE}
    container_name: ${DB_CONTAINER}
    ports:
      - "${DB_EXPORT}:${DB_INPORT}"
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
        
  web:
    image: ${WEB_IMAGE}
    container_name: ${WEB_CONTAINER}
    ports:
      - "${APP_EXPORT}:${APP_INPORT}"
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
  